### ISSUE TITLE
Executed script shows as a zombie

### ISSUE THREAD

**Issue by 0xFACE** [pilluli/service.xbmc.callbacks#1]
Top/ps tool shows executed callback scripts (bash or python) as a zombie process.

**Comment by pilluli** [comment]
Does it happen with all callback scripts? I mean all types of callbacks, such as start, file play/stop, screensaver starts/stops???

**Comment by 0xFACE** [comment]
I have following callbacks active:
    setting id="screensaver_starts" value="/home/xbian/knob_red.py"
    setting id="screensaver_stops" value="/home/xbian/knob_blue.py" 
    setting id="player_pauses" value="/home/xbian/knob_mag.py"
    setting id="player_resumes" value="/home/xbian/knob_blue.py"
Happens to all of them to be a zombie.

**Comment by pilluli** [comment]
Could you please try the latest commit? Thanks.

**Comment by 0xFACE** [comment]
Looks ok, so far there is no one zombie on my system ;-)
Thanks.
